[2025-02-26T15:38:46.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T15:38:46.697+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection manual__2025-02-26T15:38:43.595912+00:00 [queued]>
[2025-02-26T15:38:46.700+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection manual__2025-02-26T15:38:43.595912+00:00 [queued]>
[2025-02-26T15:38:46.700+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-26T15:38:46.784+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2025-02-26 15:38:43.595912+00:00
[2025-02-26T15:38:46.788+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-26T15:38:46.789+0000] {standard_task_runner.py:72} INFO - Started process 114 to run task
[2025-02-26T15:38:46.789+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection', 'test_postgres_connection', 'manual__2025-02-26T15:38:43.595912+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/test_connection.py', '--cfg-path', '/tmp/tmpar4guax9']
[2025-02-26T15:38:46.790+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask test_postgres_connection
[2025-02-26T15:38:46.813+0000] {task_command.py:467} INFO - Running <TaskInstance: test_postgres_connection.test_postgres_connection manual__2025-02-26T15:38:43.595912+00:00 [running]> on host c0a08f1bf075
[2025-02-26T15:38:46.849+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T15:38:43.595912+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T15:38:43.595912+00:00'
[2025-02-26T15:38:46.850+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-26T15:38:46.850+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-26T15:38:46.850+0000] {logging_mixin.py:190} INFO - Current task name:test_postgres_connection state:running start_date:2025-02-26 15:38:46.697312+00:00
[2025-02-26T15:38:46.850+0000] {logging_mixin.py:190} INFO - Dag name:test_postgres_connection and current dag run status:running
[2025-02-26T15:38:46.851+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T15:38:46.851+0000] {test_connection.py:51} INFO - Testing PostgreSQL connection
[2025-02-26T15:38:46.851+0000] {test_connection.py:62} INFO - Connecting to PostgreSQL at postgres:5432/datawarehouse
[2025-02-26T15:38:46.852+0000] {test_connection.py:90} ERROR - Connection test failed: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user "datauser"

[2025-02-26T15:38:46.852+0000] {python.py:240} INFO - Done. Returned value was: False
[2025-02-26T15:38:46.871+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T15:38:46.872+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=test_postgres_connection, task_id=test_postgres_connection, run_id=manual__2025-02-26T15:38:43.595912+00:00, execution_date=20250226T153843, start_date=20250226T153846, end_date=20250226T153846
[2025-02-26T15:38:46.890+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-26T15:38:46.890+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-26T15:38:46.890+0000] {logging_mixin.py:190} INFO - Dag name:test_postgres_connection queued_at:2025-02-26 15:38:43.614706+00:00
[2025-02-26T15:38:46.890+0000] {logging_mixin.py:190} INFO - Task hostname:c0a08f1bf075 operator:PythonOperator
[2025-02-26T15:38:46.929+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-26T15:38:46.939+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T15:38:46.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
