[2025-02-26T17:08:58.190+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T17:08:58.200+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_cleaning_ecommerce_postgres.clean_data_task manual__2025-02-26T17:08:54.389527+00:00 [queued]>
[2025-02-26T17:08:58.204+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_cleaning_ecommerce_postgres.clean_data_task manual__2025-02-26T17:08:54.389527+00:00 [queued]>
[2025-02-26T17:08:58.204+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-26T17:08:58.212+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): clean_data_task> on 2025-02-26 17:08:54.389527+00:00
[2025-02-26T17:08:58.217+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-26T17:08:58.218+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2025-02-26T17:08:58.219+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_ecommerce_postgres', 'clean_data_task', 'manual__2025-02-26T17:08:54.389527+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_ecommerce_postgres.py', '--cfg-path', '/tmp/tmpzjd8zduu']
[2025-02-26T17:08:58.220+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask clean_data_task
[2025-02-26T17:08:58.477+0000] {task_command.py:467} INFO - Running <TaskInstance: data_cleaning_ecommerce_postgres.clean_data_task manual__2025-02-26T17:08:54.389527+00:00 [running]> on host 37aea781b896
[2025-02-26T17:08:58.506+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_cleaning_ecommerce_postgres' AIRFLOW_CTX_TASK_ID='clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T17:08:54.389527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T17:08:54.389527+00:00'
[2025-02-26T17:08:58.507+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-26T17:08:58.507+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-26T17:08:58.507+0000] {logging_mixin.py:190} INFO - Current task name:clean_data_task state:running start_date:2025-02-26 17:08:58.200385+00:00
[2025-02-26T17:08:58.507+0000] {logging_mixin.py:190} INFO - Dag name:data_cleaning_ecommerce_postgres and current dag run status:running
[2025-02-26T17:08:58.507+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T17:08:58.507+0000] {data_cleaning_ecommerce_postgres.py:328} INFO - Starting e-commerce data cleaning process
[2025-02-26T17:08:58.508+0000] {data_cleaning_ecommerce_postgres.py:60} INFO - Establishing database connection
[2025-02-26T17:08:58.508+0000] {data_cleaning_ecommerce_postgres.py:69} INFO - Connecting to PostgreSQL at data-postgres:5432/datawarehouse
[2025-02-26T17:08:58.508+0000] {data_cleaning_ecommerce_postgres.py:70} INFO - User: datauser
[2025-02-26T17:08:58.508+0000] {data_cleaning_ecommerce_postgres.py:71} INFO - Password: datapass
[2025-02-26T17:08:58.510+0000] {data_cleaning_ecommerce_postgres.py:79} INFO - Database connection established successfully
[2025-02-26T17:08:58.510+0000] {data_cleaning_ecommerce_postgres.py:96} INFO - Extracting data from ecommerce_orders table
[2025-02-26T17:08:58.513+0000] {warnings.py:112} WARNING - /opt/***/dags/data_cleaning_ecommerce_postgres.py:99: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

[2025-02-26T17:08:58.515+0000] {data_cleaning_ecommerce_postgres.py:100} INFO - Successfully extracted 103 records
[2025-02-26T17:08:58.516+0000] {logging_mixin.py:190} INFO - Original DataFrame:
[2025-02-26T17:08:58.521+0000] {logging_mixin.py:190} INFO -    order_id customer        order_date     product  quantity   price
0      1001    alice        2021/01/15      Laptop       1.0  1200.0
1      1002     Bob         15-01-2021  smartphone       2.0   800.0
2      1003  charlie  January 15, 2021      Tablet       NaN   400.0
3      1002      Bob        15/01/2021  Smartphone       2.0   800.0
4      1004    David        2021.01.16     laptop        1.0  1200.0
[2025-02-26T17:08:58.522+0000] {data_cleaning_ecommerce_postgres.py:337} INFO - Starting data transformation pipeline
[2025-02-26T17:08:58.522+0000] {data_cleaning_ecommerce_postgres.py:121} INFO - Handling missing values
[2025-02-26T17:08:58.522+0000] {data_cleaning_ecommerce_postgres.py:124} INFO - Found 20 missing quantity values and 14 missing price values
[2025-02-26T17:08:58.523+0000] {data_cleaning_ecommerce_postgres.py:129} INFO - Missing values handled successfully
[2025-02-26T17:08:58.523+0000] {data_cleaning_ecommerce_postgres.py:143} INFO - Removing duplicate records
[2025-02-26T17:08:58.523+0000] {data_cleaning_ecommerce_postgres.py:147} INFO - Removed 2 duplicate records
[2025-02-26T17:08:58.524+0000] {data_cleaning_ecommerce_postgres.py:161} INFO - Standardizing data formats
[2025-02-26T17:08:58.525+0000] {warnings.py:112} WARNING - /opt/***/dags/data_cleaning_ecommerce_postgres.py:174: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_copy['order_date'] = pd.to_datetime(df_copy['order_date'],

[2025-02-26T17:08:58.525+0000] {data_cleaning_ecommerce_postgres.py:360} ERROR - Data cleaning process failed: time data "15-01-2021" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2025-02-26T17:08:58.525+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_cleaning_ecommerce_postgres.py", line 340, in load_and_clean_data
    df_clean = standardize_formats(df_clean)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_cleaning_ecommerce_postgres.py", line 174, in standardize_formats
    df_copy['order_date'] = pd.to_datetime(df_copy['order_date'],
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 355, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "15-01-2021" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2025-02-26T17:08:58.530+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-26T17:08:58.530+0000] {logging_mixin.py:190} INFO - Task start:2025-02-26 17:08:58.200385+00:00 end:2025-02-26 17:08:58.530578+00:00 duration:0.330193
[2025-02-26T17:08:58.531+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): clean_data_task> dag:<DAG: data_cleaning_ecommerce_postgres> dagrun:<DagRun data_cleaning_ecommerce_postgres @ 2025-02-26 17:08:54.389527+00:00: manual__2025-02-26T17:08:54.389527+00:00, state:running, queued_at: 2025-02-26 17:08:54.405805+00:00. externally triggered: True>
[2025-02-26T17:08:58.531+0000] {logging_mixin.py:190} INFO - Failure caused by time data "15-01-2021" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2025-02-26T17:08:58.531+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_cleaning_ecommerce_postgres, task_id=clean_data_task, run_id=manual__2025-02-26T17:08:54.389527+00:00, execution_date=20250226T170854, start_date=20250226T170858, end_date=20250226T170858
[2025-02-26T17:08:58.542+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T17:08:58.543+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task clean_data_task (time data "15-01-2021" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.; 92)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_cleaning_ecommerce_postgres.py", line 340, in load_and_clean_data
    df_clean = standardize_formats(df_clean)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_cleaning_ecommerce_postgres.py", line 174, in standardize_formats
    df_copy['order_date'] = pd.to_datetime(df_copy['order_date'],
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 355, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "15-01-2021" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2025-02-26T17:08:58.562+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-26T17:08:58.698+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T17:08:58.699+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
